name: Check and build using (Nix)

on:
  push:
    branches:
      - "*"
    tags:
      - "v*.*.*"
  pull_request:
    branches:
      - "*"

jobs:
    build_and_test_nix:
        name: Test and build canonical-ledger-state using Nix
        runs-on: ubuntu-latest
        strategy:
          matrix:
            include:
              - compiler: ghc912
              - compiler: ghc910
              - compiler: ghc984
        steps:
        - name: git checkout
          uses: actions/checkout@v3
        - name: Install Nix
          uses: DeterminateSystems/nix-installer-action@main
        - uses: DeterminateSystems/magic-nix-cache-action@main
        - name: Set up cache
          uses: actions/cache@v3
          with:
            path: |
                dist-newstyle/
            key: canonical-ledger-state-${{ hashFiles('cabal.project','flake.lock') }}
        - uses: lriesebos/nix-develop-command@v1
          with:
            devshell: ${{ matrix.compiler }}
            options: "--accept-flake-config"
        - name: Build
          run: cabal build all
        - name: Test
          run: cabal test all